// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF9E1PyquyJsftB31xjK2TrJdN8fMIBbY',
    appId: '1:857171577252:web:83c7edd4c1f651609d1931',
    messagingSenderId: '857171577252',
    projectId: 'appinio-restaurant-booking-app',
    authDomain: 'appinio-restaurant-booking-app.firebaseapp.com',
    storageBucket: 'appinio-restaurant-booking-app.appspot.com',
    measurementId: 'G-VC1C66BM0F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3qKWwRb1m9hLTMsdERSOi8hEBWJyZSrw',
    appId: '1:857171577252:ios:5009db7fc6c717fd9d1931',
    messagingSenderId: '857171577252',
    projectId: 'appinio-restaurant-booking-app',
    storageBucket: 'appinio-restaurant-booking-app.appspot.com',
    iosBundleId: 'com.example.restaurantBookingApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ddjiewLKgdq82JVvQY2aC_KutOKklyQ',
    appId: '1:857171577252:android:f6ecd83da17f60899d1931',
    messagingSenderId: '857171577252',
    projectId: 'appinio-restaurant-booking-app',
    storageBucket: 'appinio-restaurant-booking-app.appspot.com',
  );

}